"""Initial database creation

Revision ID: 350f988b15b8
Revises: 
Create Date: 2025-11-07 01:37:56.549879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350f988b15b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('input_file', sa.String(length=512), nullable=True),
    sa.Column('output_dir', sa.String(length=512), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('min_samples', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_predictions_output_dir'), ['output_dir'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_project_id'), ['project_id'], unique=False)

    op.create_table('site_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('earfcn_or_narfcn', sa.Integer(), nullable=False),
    sa.Column('site_key_inferred', sa.String(length=100), nullable=False),
    sa.Column('pci_or_psi', sa.Integer(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=True),
    sa.Column('lat_pred', sa.Float(), nullable=True),
    sa.Column('lon_pred', sa.Float(), nullable=True),
    sa.Column('azimuth_deg_5', sa.Integer(), nullable=True),
    sa.Column('azimuth_deg_5_soft', sa.Integer(), nullable=True),
    sa.Column('azimuth_deg_label_soft', sa.String(length=50), nullable=True),
    sa.Column('azimuth_adjustment_deg', sa.Float(), nullable=True),
    sa.Column('template_spacing_deg', sa.Float(), nullable=True),
    sa.Column('beamwidth_deg_est', sa.Integer(), nullable=True),
    sa.Column('cell_id_representative', sa.String(length=255), nullable=True),
    sa.Column('sector_count', sa.Integer(), nullable=True),
    sa.Column('azimuth_reliability', sa.Float(), nullable=True),
    sa.Column('spacing_used', sa.String(length=50), nullable=True),
    sa.Column('range_mae_m', sa.Float(), nullable=True),
    sa.Column('site_spread_m', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network', 'earfcn_or_narfcn', 'site_key_inferred', 'pci_or_psi', 'project_id', name='uq_site_ml_key_v2')
    )
    with op.batch_alter_table('site_ml', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_ml_earfcn_or_narfcn'), ['earfcn_or_narfcn'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_ml_network'), ['network'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_ml_pci_or_psi'), ['pci_or_psi'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_ml_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_ml_site_key_inferred'), ['site_key_inferred'], unique=False)

    op.create_table('site_noMl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('earfcn_or_narfcn', sa.Integer(), nullable=False),
    sa.Column('site_key_inferred', sa.String(length=100), nullable=False),
    sa.Column('pci_or_psi', sa.Integer(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=True),
    sa.Column('lat_pred', sa.Float(), nullable=True),
    sa.Column('lon_pred', sa.Float(), nullable=True),
    sa.Column('azimuth_deg_5', sa.Integer(), nullable=True),
    sa.Column('azimuth_deg_5_soft', sa.Integer(), nullable=True),
    sa.Column('azimuth_deg_label_soft', sa.String(length=50), nullable=True),
    sa.Column('azimuth_adjustment_deg', sa.Float(), nullable=True),
    sa.Column('template_spacing_deg', sa.Float(), nullable=True),
    sa.Column('beamwidth_deg_est', sa.Integer(), nullable=True),
    sa.Column('median_sample_distance_m', sa.Float(), nullable=True),
    sa.Column('cell_id_representative', sa.String(length=255), nullable=True),
    sa.Column('sector_count', sa.Integer(), nullable=True),
    sa.Column('azimuth_reliability', sa.Float(), nullable=True),
    sa.Column('spacing_used', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network', 'earfcn_or_narfcn', 'site_key_inferred', 'pci_or_psi', 'project_id', name='uq_site_noml_key_v2')
    )
    with op.batch_alter_table('site_noMl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_noMl_earfcn_or_narfcn'), ['earfcn_or_narfcn'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_noMl_network'), ['network'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_noMl_pci_or_psi'), ['pci_or_psi'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_noMl_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_noMl_site_key_inferred'), ['site_key_inferred'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_noMl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_noMl_site_key_inferred'))
        batch_op.drop_index(batch_op.f('ix_site_noMl_project_id'))
        batch_op.drop_index(batch_op.f('ix_site_noMl_pci_or_psi'))
        batch_op.drop_index(batch_op.f('ix_site_noMl_network'))
        batch_op.drop_index(batch_op.f('ix_site_noMl_earfcn_or_narfcn'))

    op.drop_table('site_noMl')
    with op.batch_alter_table('site_ml', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_ml_site_key_inferred'))
        batch_op.drop_index(batch_op.f('ix_site_ml_project_id'))
        batch_op.drop_index(batch_op.f('ix_site_ml_pci_or_psi'))
        batch_op.drop_index(batch_op.f('ix_site_ml_network'))
        batch_op.drop_index(batch_op.f('ix_site_ml_earfcn_or_narfcn'))

    op.drop_table('site_ml')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_project_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_output_dir'))
        batch_op.drop_index(batch_op.f('ix_predictions_filename'))

    op.drop_table('predictions')
    # ### end Alembic commands ###
