"""Initial database setup

Revision ID: b9dce3533323
Revises: 
Create Date: 2025-11-03 18:25:39.447024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9dce3533323'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('output_dir', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('min_samples', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_project_id'), ['project_id'], unique=False)

    op.create_table('site_Ml',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=True),
    sa.Column('earfcn_or_narfcn', sa.Float(), nullable=True),
    sa.Column('site_key_inferred', sa.Integer(), nullable=True),
    sa.Column('pci_or_psi', sa.Float(), nullable=True),
    sa.Column('samples', sa.Integer(), nullable=True),
    sa.Column('lat_pred', sa.Float(), nullable=True),
    sa.Column('lon_pred', sa.Float(), nullable=True),
    sa.Column('azimuth_deg_5', sa.Integer(), nullable=True),
    sa.Column('azimuth_deg_5_soft', sa.Integer(), nullable=True),
    sa.Column('azimuth_deg_label_soft', sa.String(length=100), nullable=True),
    sa.Column('azimuth_adjustment_deg', sa.Float(), nullable=True),
    sa.Column('template_spacing_deg', sa.Float(), nullable=True),
    sa.Column('beamwidth_deg_est', sa.Integer(), nullable=True),
    sa.Column('median_sample_distance_m', sa.Float(), nullable=True),
    sa.Column('cell_id_representative', sa.Integer(), nullable=True),
    sa.Column('sector_count', sa.Float(), nullable=True),
    sa.Column('azimuth_reliability', sa.Float(), nullable=True),
    sa.Column('spacing_used', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_Ml', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_Ml_network'), ['network'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_Ml_pci_or_psi'), ['pci_or_psi'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_Ml_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_Ml_site_key_inferred'), ['site_key_inferred'], unique=False)

    op.create_table('site_noMl',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=True),
    sa.Column('earfcn_or_narfcn', sa.Float(), nullable=True),
    sa.Column('site_key_inferred', sa.Integer(), nullable=True),
    sa.Column('pci_or_psi', sa.Float(), nullable=True),
    sa.Column('samples', sa.Integer(), nullable=True),
    sa.Column('lat_pred', sa.Float(), nullable=True),
    sa.Column('lon_pred', sa.Float(), nullable=True),
    sa.Column('azimuth_deg_5', sa.Integer(), nullable=True),
    sa.Column('azimuth_deg_5_soft', sa.Integer(), nullable=True),
    sa.Column('azimuth_deg_label_soft', sa.String(length=100), nullable=True),
    sa.Column('azimuth_adjustment_deg', sa.Float(), nullable=True),
    sa.Column('template_spacing_deg', sa.Float(), nullable=True),
    sa.Column('beamwidth_deg_est', sa.Integer(), nullable=True),
    sa.Column('median_sample_distance_m', sa.Float(), nullable=True),
    sa.Column('cell_id_representative', sa.Integer(), nullable=True),
    sa.Column('sector_count', sa.Float(), nullable=True),
    sa.Column('azimuth_reliability', sa.Float(), nullable=True),
    sa.Column('spacing_used', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_noMl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_noMl_network'), ['network'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_noMl_pci_or_psi'), ['pci_or_psi'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_noMl_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_noMl_site_key_inferred'), ['site_key_inferred'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_noMl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_noMl_site_key_inferred'))
        batch_op.drop_index(batch_op.f('ix_site_noMl_project_id'))
        batch_op.drop_index(batch_op.f('ix_site_noMl_pci_or_psi'))
        batch_op.drop_index(batch_op.f('ix_site_noMl_network'))

    op.drop_table('site_noMl')
    with op.batch_alter_table('site_Ml', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_Ml_site_key_inferred'))
        batch_op.drop_index(batch_op.f('ix_site_Ml_project_id'))
        batch_op.drop_index(batch_op.f('ix_site_Ml_pci_or_psi'))
        batch_op.drop_index(batch_op.f('ix_site_Ml_network'))

    op.drop_table('site_Ml')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_project_id'))

    op.drop_table('predictions')
    # ### end Alembic commands ###
